hydra:
    run:
        dir: .

data_path: data/raw/heart.csv
model_output_path: models/model.pkl
transformer_path: models/transformer.pkl
logging_config: ml_project/configs/logging_config.yaml
splitting_params:
    val_size: 0.25
    test_size: 0.1
    random_state: 42
feature_params:
    categorical_columns: 
        - sex
        - cp
        - fbs
        - restecg
        - slope
        - thal
    target_column: target
    features_to_drop: []

model_type: sklearn.svm.SVC
model_params:
    C: 0.1
    kernel: linear
random_state: 42