version: 1.0
formatters:
    simple:
        class: logging.Formatter
        format: '[%(asctime)s] %(levelname)s: %(message)-15s'
        datefmt: '%Y-%m-%d %H:%M:%S'
handlers:
    stream_handler:
        class: logging.StreamHandler
        stream: ext://sys.stdout
        level: DEBUG
loggers:
    heart_disease:
        level: DEBUG
        handlers: [stream_handler]
root:
    level: DEBUG
    handlers: [stream_handler]